jwt:
  token:
    sercert: jwtemployee
    validty: 864000000
server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/user
    username: postgres
    password: 1273
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true